/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package espensestracker.views;

import espensestracker.util.IconCreator;
import espensestracker.util.ViewIndex;
import espensestracker.views.CategoryListView;
import espensestracker.views.ExpensesListView;
import espensestracker.views.IncomeListView;
import espensestracker.views.DashboardDataView;
import espensestracker.viewer.ViewHandler;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JTabbedPane;

public class DashboardView extends javax.swing.JFrame {

    public DashboardView() {
        loadIcon();
        this.setTitle("Expenses Tracker");
        initComponents();
        loadDashboardData(1);

    }

    private void loadDashboardData(int month) {
        ViewHandler.OpenViewer(ViewIndex.SUMMARY_VIEW, dashboardMonthCmb.getSelectedIndex() + 1, this.mainContainer);

    }

    private void loadIcon() {
        try {
            Image appIcon = new IconCreator().loadApplicationIcon();
            if (appIcon != null) {
                setIconImage(appIcon);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabsPanel = new javax.swing.JTabbedPane();
        dashboardContainer = new javax.swing.JPanel();
        dashboardMonthCmb = new javax.swing.JComboBox<>();
        dashboardScorllPanel = new javax.swing.JScrollPane();
        mainContainer = new javax.swing.JPanel();
        expensesContainer = new javax.swing.JPanel();
        expensesViewContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        expensesMonthCmb = new javax.swing.JComboBox<>();
        incomeContainer = new javax.swing.JPanel();
        incomeViewContainer = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        incomeMonthCmb = new javax.swing.JComboBox<>();
        categoryContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(25, 144, 234));

        TabsPanel.setBackground(new java.awt.Color(131, 188, 231));
        TabsPanel.setForeground(new java.awt.Color(51, 51, 51));
        TabsPanel.setToolTipText("");
        TabsPanel.setName(""); // NOI18N
        TabsPanel.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                TabsPanelStateChanged(evt);
            }
        });

        dashboardContainer.setBackground(new java.awt.Color(25, 144, 234));

        dashboardMonthCmb.setBackground(new java.awt.Color(159, 199, 247));
        dashboardMonthCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        dashboardMonthCmb.setToolTipText("Select month");
        dashboardMonthCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dashboardMonthCmbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout mainContainerLayout = new javax.swing.GroupLayout(mainContainer);
        mainContainer.setLayout(mainContainerLayout);
        mainContainerLayout.setHorizontalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 929, Short.MAX_VALUE)
        );
        mainContainerLayout.setVerticalGroup(
            mainContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        dashboardScorllPanel.setViewportView(mainContainer);

        javax.swing.GroupLayout dashboardContainerLayout = new javax.swing.GroupLayout(dashboardContainer);
        dashboardContainer.setLayout(dashboardContainerLayout);
        dashboardContainerLayout.setHorizontalGroup(
            dashboardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(dashboardScorllPanel)
        );
        dashboardContainerLayout.setVerticalGroup(
            dashboardContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashboardContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dashboardMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dashboardScorllPanel))
        );

        TabsPanel.addTab("Home", null, dashboardContainer, "");

        expensesContainer.setBackground(new java.awt.Color(228, 239, 247));

        expensesViewContainer.setBackground(new java.awt.Color(228, 239, 247));

        javax.swing.GroupLayout expensesViewContainerLayout = new javax.swing.GroupLayout(expensesViewContainer);
        expensesViewContainer.setLayout(expensesViewContainerLayout);
        expensesViewContainerLayout.setHorizontalGroup(
            expensesViewContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 850, Short.MAX_VALUE)
        );
        expensesViewContainerLayout.setVerticalGroup(
            expensesViewContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 461, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(25, 144, 234));

        expensesMonthCmb.setBackground(new java.awt.Color(159, 199, 247));
        expensesMonthCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        expensesMonthCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                expensesMonthCmbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expensesMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(expensesMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout expensesContainerLayout = new javax.swing.GroupLayout(expensesContainer);
        expensesContainer.setLayout(expensesContainerLayout);
        expensesContainerLayout.setHorizontalGroup(
            expensesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensesContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(expensesViewContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        expensesContainerLayout.setVerticalGroup(
            expensesContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(expensesContainerLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(expensesViewContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        TabsPanel.addTab("Expenses", expensesContainer);
        expensesContainer.getAccessibleContext().setAccessibleName("");

        incomeContainer.setBackground(new java.awt.Color(228, 239, 247));
        incomeContainer.setName(""); // NOI18N

        incomeViewContainer.setBackground(new java.awt.Color(228, 239, 247));

        javax.swing.GroupLayout incomeViewContainerLayout = new javax.swing.GroupLayout(incomeViewContainer);
        incomeViewContainer.setLayout(incomeViewContainerLayout);
        incomeViewContainerLayout.setHorizontalGroup(
            incomeViewContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
        );
        incomeViewContainerLayout.setVerticalGroup(
            incomeViewContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 448, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(25, 144, 234));

        incomeMonthCmb.setBackground(new java.awt.Color(159, 199, 247));
        incomeMonthCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        incomeMonthCmb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                incomeMonthCmbItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incomeMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incomeMonthCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout incomeContainerLayout = new javax.swing.GroupLayout(incomeContainer);
        incomeContainer.setLayout(incomeContainerLayout);
        incomeContainerLayout.setHorizontalGroup(
            incomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(incomeContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(incomeViewContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        incomeContainerLayout.setVerticalGroup(
            incomeContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(incomeContainerLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(incomeViewContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        TabsPanel.addTab("Income", incomeContainer);

        categoryContainer.setBackground(new java.awt.Color(228, 239, 247));

        javax.swing.GroupLayout categoryContainerLayout = new javax.swing.GroupLayout(categoryContainer);
        categoryContainer.setLayout(categoryContainerLayout);
        categoryContainerLayout.setHorizontalGroup(
            categoryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        categoryContainerLayout.setVerticalGroup(
            categoryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );

        TabsPanel.addTab("Category", categoryContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabsPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabsPanel)
        );

        TabsPanel.getAccessibleContext().setAccessibleName("tablist");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incomeMonthCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_incomeMonthCmbItemStateChanged
        ViewHandler.monthOptionChange(incomeMonthCmb.getSelectedIndex() + 1, ViewIndex.INCOME_VIEW, this.incomeViewContainer);
    }//GEN-LAST:event_incomeMonthCmbItemStateChanged

    private void dashboardMonthCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dashboardMonthCmbItemStateChanged
        ViewHandler.monthOptionChange(dashboardMonthCmb.getSelectedIndex() + 1, ViewIndex.SUMMARY_VIEW, this.mainContainer);
    }//GEN-LAST:event_dashboardMonthCmbItemStateChanged

    private void expensesMonthCmbItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_expensesMonthCmbItemStateChanged
        ViewHandler.monthOptionChange(expensesMonthCmb.getSelectedIndex() + 1, ViewIndex.EXPENSES_VIEW, this.expensesViewContainer);
    }//GEN-LAST:event_expensesMonthCmbItemStateChanged

    private void TabsPanelStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_TabsPanelStateChanged
        System.out.println("Property changed");
        JTabbedPane tabbedPane = (JTabbedPane) evt.getSource();
        int selectedIndex = tabbedPane.getSelectedIndex();
        switch (selectedIndex) {
            case 0:
                ViewHandler.OpenViewer(ViewIndex.SUMMARY_VIEW, dashboardMonthCmb.getSelectedIndex() + 1, this.mainContainer);
                break;
            case 1:
                ViewHandler.OpenViewer(ViewIndex.EXPENSES_VIEW, expensesMonthCmb.getSelectedIndex() + 1, this.expensesViewContainer);
                break;
            case 2:
                ViewHandler.OpenViewer(ViewIndex.INCOME_VIEW, incomeMonthCmb.getSelectedIndex() + 1, this.incomeViewContainer);
                break;
            case 3:
                ViewHandler.OpenViewer(ViewIndex.CATEGORY_VIEW, 1, this.categoryContainer);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_TabsPanelStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabsPanel;
    private javax.swing.JPanel categoryContainer;
    private javax.swing.JPanel dashboardContainer;
    private javax.swing.JComboBox<String> dashboardMonthCmb;
    private javax.swing.JScrollPane dashboardScorllPanel;
    private javax.swing.JPanel expensesContainer;
    private javax.swing.JComboBox<String> expensesMonthCmb;
    private javax.swing.JPanel expensesViewContainer;
    private javax.swing.JPanel incomeContainer;
    private javax.swing.JComboBox<String> incomeMonthCmb;
    private javax.swing.JPanel incomeViewContainer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel mainContainer;
    // End of variables declaration//GEN-END:variables
}
