/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package espensestracker.views;

import espensestracker.util.Formatter;
import espensestracker.controller.ExpensesController;
import espensestracker.controller.IncomeController;
import espensestracker.dto.ExpensesListDto;
import espensestracker.dto.IncomeListDto;
import espensestracker.views.IncomeAddView;
import espensestracker.views.IncomeListView;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import espensestracker.controller.IExpensesController;
import espensestracker.viewer.ViewHandler;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Chamath
 */
public class ExpensesListView extends javax.swing.JPanel {

    private IExpensesController expenseController;
    private int currentEditingRowIndex = -1;
    private ArrayList<ExpensesListDto> currentExpenses;
    private int currentMonth;

    public ExpensesListView(int month) {
        currentExpenses = new ArrayList();
        System.out.println("Expenses list view called");
        currentMonth = month;
        initComponents();
        DefaultTableCellRenderer tableCellRenderer = new DefaultTableCellRenderer();
        tableCellRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        TableColumn tableColumn = tblExpenses.getColumnModel().getColumn(1);
        tblExpenses.setBackground(UIManager.getColor(new JTableHeader().getBackground()));
        tableColumn.setCellRenderer(tableCellRenderer);
        expenseController = new ExpensesController();
        loadExpensesData(month);
//        tblExpenses.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//            public void valueChanged(ListSelectionEvent event) {
//                Object a = tblExpenses.getValueAt(tblExpenses.getSelectedRow(), 0);
//                System.out.println(tblExpenses.getValueAt(tblExpenses.getSelectedRow(), 0).toString());
//            }
//        });

        tblExpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = tblExpenses.rowAtPoint(evt.getPoint());
                int col = tblExpenses.columnAtPoint(evt.getPoint());
                currentEditingRowIndex = row;
                btnExpenseEdit.setEnabled(true);
            }
        });
    }

    private double loadExpensesData(int month) {
        double total = 0.00;
        try {
            currentExpenses = expenseController.getExpensesListByMonth(month);
            DefaultTableModel model = (DefaultTableModel) tblExpenses.getModel();
            model.setNumRows(0);
            total = currentExpenses.stream().map((exp) -> {
                model.addRow(new Object[]{exp.getCategoryName(),
                    Formatter.currencyFormat(exp.getAmount())});
                return exp;
            }).map((expp) -> expp.getAmount()).reduce(total, (accumulator, _item) -> accumulator + _item);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(IncomeListView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblExpenses = new javax.swing.JTable();
        btnExpenseAdd = new javax.swing.JButton();
        btnExpenseEdit = new javax.swing.JButton();

        setBackground(new java.awt.Color(228, 239, 247));
        setPreferredSize(new java.awt.Dimension(150, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Expenses");
        jLabel1.setToolTipText("");

        jLabel2.setText("Available Expenses");
        jLabel2.setToolTipText("");

        tblExpenses.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tblExpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblExpenses.setShowHorizontalLines(false);
        tblExpenses.setShowVerticalLines(false);
        tblExpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblExpensesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblExpenses);

        btnExpenseAdd.setBackground(new java.awt.Color(159, 199, 247));
        btnExpenseAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExpenseAdd.setForeground(new java.awt.Color(25, 144, 234));
        btnExpenseAdd.setText("Add New");
        btnExpenseAdd.setToolTipText("");
        btnExpenseAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenseAddActionPerformed(evt);
            }
        });

        btnExpenseEdit.setBackground(new java.awt.Color(159, 199, 247));
        btnExpenseEdit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnExpenseEdit.setForeground(new java.awt.Color(25, 144, 234));
        btnExpenseEdit.setText("Edit");
        btnExpenseEdit.setToolTipText("");
        btnExpenseEdit.setEnabled(false);
        btnExpenseEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExpenseEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExpenseAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExpenseEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(0, 416, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExpenseAdd)
                    .addComponent(btnExpenseEdit))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        jLabel1.getAccessibleContext().setAccessibleName("expensesLabel");
    }// </editor-fold>//GEN-END:initComponents

    private void btnExpenseAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenseAddActionPerformed
        ExpensesAddView expenseView = new ExpensesAddView(null, true);
        expenseView.setLocationRelativeTo(null);
        expenseView.setVisible(true);
    }//GEN-LAST:event_btnExpenseAddActionPerformed

    private void tblExpensesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblExpensesMouseClicked
        int row = tblExpenses.rowAtPoint(evt.getPoint());
        int col = tblExpenses.columnAtPoint(evt.getPoint());
        if (row >= 0 && col >= 0) {

        }
    }//GEN-LAST:event_tblExpensesMouseClicked

    private void btnExpenseEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExpenseEditActionPerformed
        System.out.println(this.currentEditingRowIndex);
        if (this.currentEditingRowIndex > -1 && currentExpenses.size() > 0) {
            ExpensesListDto editingRow = currentExpenses.get(currentEditingRowIndex);
            ExpensesAddView expenseView = new ExpensesAddView(null, true, editingRow, currentEditingRowIndex);
            expenseView.setLocationRelativeTo(null);
            expenseView.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                    System.out.println("Espenses Edit closed");
                    currentEditingRowIndex = -1;
                    loadExpensesData(currentMonth);
                }
            });
            expenseView.setVisible(true);
        }
    }//GEN-LAST:event_btnExpenseEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExpenseAdd;
    private javax.swing.JButton btnExpenseEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblExpenses;
    // End of variables declaration//GEN-END:variables
}
