/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package espensestracker.views;

import espensestracker.util.Formatter;
import espensestracker.controller.IncomeController;
import espensestracker.dto.ExpensesListDto;
import espensestracker.dto.IncomeListDto;
import espensestracker.views.DashboardDataView;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import espensestracker.controller.IIncomeController;

/**
 *
 * @author Aravinda
 */
public class IncomeListView extends javax.swing.JPanel {

    private IIncomeController incomeControllerInf;

    /**
     * Creates new form IncomeView
     */
    public IncomeListView(int month) {
        System.out.println("Income view called");
        initComponents();
        DefaultTableCellRenderer tableCellRenderer = new DefaultTableCellRenderer();
        tableCellRenderer.setHorizontalAlignment(SwingConstants.RIGHT);
        TableColumn tableColumn = tblIncome.getColumnModel().getColumn(1);
        tblIncome.setBackground(UIManager.getColor(new JTableHeader().getBackground()));
        tableColumn.setCellRenderer(tableCellRenderer);
        incomeControllerInf = new IncomeController();
        loadIncomeData(month);
    }

    private double loadIncomeData(int month) {
        double total = 0.00;
        try {
            ArrayList<IncomeListDto> incomesByMonth = incomeControllerInf.getIncomeListByMonth(month);
            DefaultTableModel model = (DefaultTableModel) tblIncome.getModel();
            model.setNumRows(0);
            total = incomesByMonth.stream().map((icom) -> {
                model.addRow(new Object[]{icom.getCategoryName(),
                    Formatter.currencyFormat(icom.getAmount())});
                return icom;
            }).map((icomm) -> icomm.getAmount()).reduce(total, (accumulator, _item) -> accumulator + _item);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(IncomeListView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblIncome = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnIncomeAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(228, 239, 247));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Income");

        tblIncome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        tblIncome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Category", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblIncome.setShowHorizontalLines(false);
        tblIncome.setShowVerticalLines(false);
        jScrollPane1.setViewportView(tblIncome);

        jLabel2.setText("Available Incomes");

        btnIncomeAdd.setBackground(new java.awt.Color(159, 199, 247));
        btnIncomeAdd.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnIncomeAdd.setForeground(new java.awt.Color(25, 144, 234));
        btnIncomeAdd.setText("Add New");
        btnIncomeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncomeAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(btnIncomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 658, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnIncomeAdd)
                .addContainerGap(130, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncomeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncomeAddActionPerformed
        IncomeAddView addIncomeView = new IncomeAddView(null, true);
        addIncomeView.setLocationRelativeTo(null);
        addIncomeView.setVisible(true);
    }//GEN-LAST:event_btnIncomeAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIncomeAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblIncome;
    // End of variables declaration//GEN-END:variables
}
